### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by dansyrotyn** [mopsicus/unity-ios-3dtouch-fix#1]
Bug 1: It does not work. The same bug as before.
Bug 2. When we launched this script first times, it created 3 the same functions and xcode did not compile. We have to cleaned the code to make it run.
Bug 3: It does not compile on windows.

**Comment by mopsicus** [comment]
What Unity version do you use? What kind of device has been tested?
Script was tested on 5.5.3f1 and works fine.

**Comment by dansyrotyn** [comment]
We use 5.6.1f1
Device: iPhone 6s
Windows bug with: using UnityEditor.iOS.Xcode;

**Comment by mopsicus** [comment]
Ok, thx, I will test it on 5.6.1f1, I guess, generated xCode project has changed.

**Comment by sttz** [comment]
Thanks to this fix as reference, I was able to come up with an alternate implementation that does not rely on patching Unity's classes and also handles delayed touch moves. Tested on Unity 5.6.3 but should work in all recent Unity versions:
https://gist.github.com/sttz/bc2fe1ae6850bd34d1297cf8bae3c442

**Comment by mopsicus** [comment]
Cool! Glad to help you
